
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 118
#define YY_END_OF_BUFFER 119
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[427] =
    {   0,
        0,    0,    5,    5,    0,    0,    9,    9,   11,   11,
      119,  117,  116,  116,  104,  117,  117,  110,  103,  117,
       98,   99,  108,  107,   95,  106,  102,  109,   61,   60,
       96,   92,  111,   97,  112,  115,   58,   58,  100,  101,
      113,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   93,  114,   94,
      105,    6,    5,  118,    7,    7,    7,   10,    9,   12,
       11,  116,   91,    0,   69,    0,    0,    0,   77,   94,
       86,   78,    0,    0,   75,   83,   73,   84,   74,   85,
        0,   64,    1,    2,   76,   65,   61,    0,    0,   61,

       61,    0,   61,   60,   60,   60,   60,  101,   93,  100,
       82,   88,   90,   89,   81,   58,    0,    0,   79,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   20,   58,   58,   58,   58,   58,
       58,   28,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   80,   87,    6,    5,    7,    7,
        8,   10,    9,   12,   11,   69,    0,    0,    0,    0,
        0,    0,   62,    0,    0,   70,    0,   64,    2,    0,
       65,    0,   63,   61,   61,   61,   61,    0,   59,   60,
       60,   60,   60,   72,   71,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   26,   58,   58,   30,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,    0,    0,    0,    0,
        0,    0,    0,   64,    0,   65,   63,   61,    0,    0,
       59,    0,   59,   59,   60,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   13,   58,   15,   16,   58,
       58,   58,   58,   22,   23,   58,   58,   27,   58,   31,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   44,   58,   58,    0,    0,    0,    0,    0,

        0,    0,    0,   59,   59,    0,   66,   59,   59,   58,
       58,   50,   58,   58,   58,   58,   58,   58,   58,   14,
       17,   58,   58,   58,   58,   25,   58,   58,   58,   58,
       35,   58,   58,   58,   58,   58,   58,   42,   58,   58,
       46,    0,    0,    0,   67,    0,   68,   66,   59,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       21,   24,   29,   58,   58,   34,   36,   37,   38,   39,
       40,   58,   58,   58,    0,    0,   67,   68,   58,   58,
       49,   58,   58,   58,   58,   58,   58,   58,   58,   19,
       58,   58,   41,   58,   58,    4,    3,   47,   48,   51,

       52,   58,   58,   58,   58,   57,   18,   32,   33,   43,
       45,   58,   54,   58,   58,   53,   58,   58,   58,   58,
       58,   58,   58,   56,   55,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   36,   36,   38,   36,   39,   36,   40,
       36,   36,   41,   42,   43,   36,   36,   44,   36,   36,
       45,   46,   47,   48,   49,    1,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   36,   59,   60,   61,   62,
       63,   64,   36,   65,   66,   67,   68,   69,   70,   71,
       72,   73,   74,   75,   76,   77,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[78] =
    {   0,
        1,    2,    3,    1,    1,    4,    1,    1,    1,    5,
        1,    1,    6,    1,    1,    1,    7,    1,    8,    8,
        9,    9,    1,    1,    1,    1,    1,    4,    9,    9,
        9,    9,    9,    9,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,    1,    4,    1,    1,   10,    8,
        8,    9,    9,    9,    8,   10,   10,   10,   10,   10,
       10,   11,   10,   10,   11,   10,   11,   10,   11,   10,
       11,   10,   10,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[445] =
    {   0,
        0,    0,   76,   78,   79,   80,  830,  829,   82,   84,
      830,  833,   86,   92,  803,   85,   44,   72,   91,  782,
      833,  833,  801,   87,  833,   88,   86,   98,  115,  106,
      799,  833,  138,  799,   83,  833,    0,  112,  833,  833,
      798,  150,  755,  757,   88,   58,   81,   70,  758,   85,
      757,  765,   98,  746,  161,  754,  759,  833,  103,  833,
      833,    0,  813,  833,  811,  810,  794,    0,  809,    0,
      808,  191,  833,  144,  194,  153,  755,  746,  833,  833,
      833,  833,  160,  157,  833,  833,  833,  833,  833,  833,
      790,  188,  833,    0,  833,  196,  238,  219,  247,  176,

       82,  789,  145,  258,  227,  124,  204,  833,  833,  833,
      779,  833,  833,  833,  778,    0,  239,  757,  833,  144,
      739,  738,  746,  738,  735,  730,  739,  740,  727,  739,
      726,  741,  728,  734,  720,  721,  718,  718,  721,  718,
      715,    0,  160,  719,  227,  717,  226,  181,  721,  714,
      771,  167,  143,  718,  833,  833,    0,  773,  771,  770,
      833,    0,  770,    0,  769,  284,  764,  268,  291,    0,
      714,  716,  833,  294,    0,  833,  309,  833,    0,  322,
      833,  313,  326,  241,  833,  729,  706,    0,  332,  308,
      833,  727,  704,  833,  833,  705,  699,  698,  699,  697,

      708,  692,  706,  690,  686,  690,  702,  697,  685,  187,
      699,  697,  693,  685,  691,  694,    0,  680,  684,    0,
      685,  682,  655,  650,  652,  653,  660,  643,  641,  640,
      652,  632,  636,  630,  626,  602,  347,  395,  603,  589,
      349,  441,  335,  384,  358,  445,  833,  833,  260,  275,
      320,  416,  323,  322,  833,  591,  575,  528,  523,  532,
      529,  529,  515,  527,  518,    0,  520,    0,    0,  511,
      519,  508,  515,    0,    0,  509,  506,    0,  510,    0,
      505,  505,  504,  501,  511,  501,  504,  507,  506,  504,
      494,  498,    0,  486,  498,  356,    0,  485,  478,  361,

        0,  487,  496,  330,  833,  389,  500,  507,  483,  480,
      483,    0,  479,  472,  478,  468,  475,  482,  479,    0,
        0,  468,  469,  470,  461,    0,  460,  446,  453,  442,
        0,  449,  444,  446,  430,  433,  435,    0,  426,  428,
        0,  431,  431,  433,  506,  437,  529,  833,  833,  253,
      430,  427,  422,  416,  409,  424,  416,  419,  375,  375,
        0,    0,    0,  386,  382,    0,    0,    0,    0,    0,
        0,  378,  377,  363,  419,  366,  833,  833,  353,  358,
        0,  341,  347,  347,  329,  342,  340,  338,  331,    0,
      319,  307,    0,  297,  267,  833,  833,    0,    0,    0,

        0,  255,  257,  267,  248,    0,    0,    0,    0,    0,
        0,  235,    0,  239,  239,    0,  183,  183,  158,  152,
       92,   94,   52,    0,    0,  833,  589,  600,  611,  622,
      633,  644,  648,  659,  670,  681,  692,  700,  708,  719,
      724,  726,  728,  730
    } ;

static yyconst flex_int16_t yy_def[445] =
    {   0,
      426,    1,  427,  427,  428,  428,  429,  429,  430,  430,
      426,  426,  426,  426,  426,  431,  426,  426,  426,  432,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  433,  433,  426,  426,
      426,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  426,  426,  426,
      426,  434,  426,  426,  435,  435,  426,  436,  426,  437,
      426,  426,  426,  431,  426,  438,  426,  426,  426,  426,
      426,  426,  432,  439,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  440,  426,  426,  426,  426,  426,  426,

      426,  441,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  433,  431,  432,  426,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  426,  426,  434,  426,  435,  435,
      426,  436,  426,  437,  426,  426,  426,  426,  431,  442,
      426,  426,  426,  432,  443,  426,  426,  426,  440,  426,
      426,  426,  426,  426,  426,  426,  426,  444,  441,  426,
      426,  426,  426,  426,  426,  433,  433,  433,  433,  433,

      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  431,  431,  426,  426,
      432,  432,  426,  426,  426,  426,  426,  426,  444,  444,
      426,  426,  426,  426,  426,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  431,  238,  426,  426,  432,

      242,  426,  426,  426,  426,  426,  426,  426,  426,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  426,  426,  426,  426,  426,  426,  426,  426,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  426,  426,  426,  426,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  426,  426,  433,  433,  433,

      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,    0,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426
    } ;

static yyconst flex_uint16_t yy_nxt[911] =
    {   0,
       12,   13,   14,   13,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       30,   30,   31,   32,   33,   34,   35,   36,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   38,   37,   37,
       37,   37,   38,   37,   39,   12,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   37,   50,   37,   51,
       37,   37,   37,   37,   52,   53,   54,   55,   56,   57,
       37,   37,   37,   58,   59,   60,   61,   63,   64,   63,
       64,   66,   66,   71,   64,   71,   64,   72,   72,   72,
       75,   67,   67,   72,   72,   72,   77,   79,   80,   81,

       86,   78,   91,   88,   92,   92,   92,   92,  114,  115,
       93,  134,   87,   89,   90,   94,   82,  117,  425,  186,
      135,  118,   96,   95,  104,  104,  104,  104,  155,  139,
       76,   96,  140,   97,   97,   98,   98,  131,   99,  142,
      136,  187,  137,  105,  132,  109,  143,   99,  106,   75,
      133,  138,  100,  424,  146,  147,  423,  101,  102,   99,
      110,  192,  111,  112,  148,  107,  117,  149,   99,  173,
      118,  169,  169,  106,  103,  174,  174,  156,  120,  121,
      122,  151,  101,  193,  123,  102,  124,  185,  125,   76,
      126,  127,   72,   72,   72,  166,  166,  166,  128,  117,

      234,  422,  235,  196,  184,   84,   92,   92,   92,   92,
      197,  421,  185,  184,   92,   92,   92,   92,  185,  219,
      177,  178,  152,  170,  232,  178,  220,  175,  180,  181,
      228,  167,  233,  181,  420,   96,  167,   98,   98,   98,
       98,  177,  178,  185,   75,  229,  191,  178,  419,  180,
      181,   99,  270,  271,   96,  181,   97,   97,   98,   98,
      182,  168,  182,  190,  190,  183,  183,  183,  183,  191,
       99,  191,   99,  117,   96,  100,  104,  104,  104,  104,
      101,  226,  222,  185,   76,  166,  166,  166,  167,  117,
       99,   99,  223,  224,  191,  105,   75,  103,  227,  302,

      106,  418,  379,  173,  417,  101,  416,  415,  185,  237,
      237,   99,  241,  241,  303,  380,  414,  107,  413,  412,
      411,  167,  243,  302,  243,  106,  167,  244,  244,  244,
      244,  183,  183,  183,  183,  245,   76,  245,  303,   84,
      246,  246,  246,  246,  183,  183,  183,  183,  250,  410,
      191,  168,   75,  244,  244,  244,  244,  304,  173,  247,
      308,   75,  305,  247,  305,  296,  296,  300,  300,  251,
      173,  252,  305,  409,  253,  191,  246,  246,  246,  246,
      247,  304,  309,  408,  407,  247,  406,  305,  405,  305,
      404,  254,   76,  403,   84,  252,  402,  305,  401,  253,

       75,   76,  244,  244,  244,  244,   84,  307,  307,  307,
      307,  400,  399,  297,  297,  297,  297,  178,  398,  397,
      396,  178,  395,  297,  297,  297,  297,  297,  297,  306,
      394,  306,  393,  392,  307,  307,  307,  307,  178,  391,
       76,  390,  389,  178,  297,  297,  297,  297,  297,  297,
      173,  345,  345,  345,  345,  347,  347,  347,  347,  301,
      301,  301,  301,  246,  246,  246,  246,  388,  387,  301,
      301,  301,  301,  301,  301,  386,  385,  384,  181,  383,
      382,  381,  181,  376,  375,  374,   84,  373,  372,  371,
      301,  301,  301,  301,  301,  301,  370,  369,  368,  181,

      344,  367,  344,  366,  181,  345,  345,  345,  345,  346,
      365,  346,  364,  363,  347,  347,  347,  347,  307,  307,
      307,  307,  362,  361,  345,  345,  345,  345,  360,  359,
      358,  357,  356,  348,  355,  354,  353,  348,  352,  377,
      351,  350,  349,  377,  349,  343,  342,  347,  347,  347,
      347,  341,  340,  339,  348,  338,  337,  336,  335,  348,
      377,  334,  378,  333,  332,  377,  378,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  378,  315,  314,  313,  312,  378,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,

       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   74,   74,  311,   74,   74,   74,   74,
       74,   74,   74,   74,   83,   83,  310,   83,  299,   83,
       83,   83,   83,   83,   83,  116,  116,  116,  116,  157,
      298,  295,  157,  157,  157,  157,  157,  157,  157,  157,
      159,  159,  159,  159,  159,  294,  159,  159,  159,  159,
      159,  162,  293,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  164,  292,  291,  164,  164,  164,  164,  164,

      164,  164,  164,   74,   74,  290,  289,   74,  288,  287,
       74,   83,   83,  286,  285,   83,  284,  283,   83,  179,
      179,  282,  179,  179,  179,  179,  179,  179,  179,  179,
      189,  189,  189,  238,  238,  242,  242,  249,  249,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  272,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  255,  248,  248,  240,  239,  117,
      165,  163,  160,  160,  158,  236,  117,  231,  230,  225,
      221,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,

      199,  198,   84,  195,  194,  188,  176,  172,  171,  165,
      163,  161,  160,  160,  158,  154,  153,  150,  145,  144,
      141,  130,  129,  119,  113,  108,   85,   84,   73,  426,
       69,   69,   11,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,

      426,  426,  426,  426,  426,  426,  426,  426,  426,  426
    } ;

static yyconst flex_int16_t yy_chk[911] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    4,
        4,    5,    6,    9,    9,   10,   10,   13,   13,   13,
       16,    5,    6,   14,   14,   14,   17,   18,   18,   19,

       24,   17,   27,   26,   27,   27,   27,   27,   35,   35,
       28,   46,   24,   26,   26,   28,   19,   38,  423,  101,
       46,   38,   30,   28,   30,   30,   30,   30,   59,   48,
       16,   29,   48,   29,   29,   29,   29,   45,   30,   50,
       47,  101,   47,   30,   45,   33,   50,   29,   30,   74,
       45,   47,   29,  422,   53,   53,  421,   29,   29,   30,
       33,  106,   33,   33,   53,   30,   55,   53,   29,   83,
       55,   76,   76,   30,   29,   84,   84,   59,   42,   42,
       42,   55,   29,  106,   42,   29,   42,  103,   42,   74,
       42,   42,   72,   72,   72,   75,   75,   75,   42,   75,

      153,  420,  153,  120,  103,   83,   92,   92,   92,   92,
      120,  419,  103,  100,   96,   96,   96,   96,  100,  143,
       92,   92,   55,   76,  152,   92,  143,   84,   96,   96,
      148,   75,  152,   96,  418,   98,   75,   98,   98,   98,
       98,   92,   92,  100,  117,  148,  107,   92,  417,   96,
       96,   98,  210,  210,   97,   96,   97,   97,   97,   97,
       99,   75,   99,  107,  105,   99,   99,   99,   99,  105,
       97,  107,   98,  168,  104,   97,  104,  104,  104,  104,
       97,  147,  145,  184,  117,  166,  166,  166,  168,  166,
      104,   97,  145,  145,  105,  104,  169,   97,  147,  249,

      104,  415,  350,  174,  414,   97,  412,  405,  184,  169,
      169,  104,  174,  174,  250,  350,  404,  104,  403,  402,
      395,  166,  177,  249,  177,  104,  166,  177,  177,  177,
      177,  182,  182,  182,  182,  180,  169,  180,  250,  174,
      180,  180,  180,  180,  183,  183,  183,  183,  189,  394,
      190,  166,  237,  243,  243,  243,  243,  251,  241,  183,
      253,  296,  251,  183,  254,  237,  237,  241,  241,  189,
      300,  189,  304,  392,  189,  190,  245,  245,  245,  245,
      183,  254,  253,  391,  389,  183,  388,  251,  387,  254,
      386,  189,  237,  385,  241,  189,  384,  304,  383,  189,

      238,  296,  244,  244,  244,  244,  300,  306,  306,  306,
      306,  382,  380,  238,  238,  238,  238,  244,  379,  376,
      375,  244,  374,  238,  238,  238,  238,  238,  238,  252,
      373,  252,  372,  365,  252,  252,  252,  252,  244,  364,
      238,  360,  359,  244,  238,  238,  238,  238,  238,  238,
      242,  344,  344,  344,  344,  346,  346,  346,  346,  242,
      242,  242,  242,  246,  246,  246,  246,  358,  357,  242,
      242,  242,  242,  242,  242,  356,  355,  354,  246,  353,
      352,  351,  246,  343,  342,  340,  242,  339,  337,  336,
      242,  242,  242,  242,  242,  242,  335,  334,  333,  246,

      302,  332,  302,  330,  246,  302,  302,  302,  302,  303,
      329,  303,  328,  327,  303,  303,  303,  303,  307,  307,
      307,  307,  325,  324,  345,  345,  345,  345,  323,  322,
      319,  318,  317,  307,  316,  315,  314,  307,  313,  345,
      311,  310,  309,  345,  308,  299,  298,  347,  347,  347,
      347,  295,  294,  292,  307,  291,  290,  289,  288,  307,
      345,  287,  347,  286,  285,  345,  347,  284,  283,  282,
      281,  279,  277,  276,  273,  272,  271,  270,  267,  265,
      264,  263,  262,  347,  261,  260,  259,  258,  347,  427,
      427,  427,  427,  427,  427,  427,  427,  427,  427,  427,

      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  431,  431,  257,  431,  431,  431,  431,
      431,  431,  431,  431,  432,  432,  256,  432,  240,  432,
      432,  432,  432,  432,  432,  433,  433,  433,  433,  434,
      239,  236,  434,  434,  434,  434,  434,  434,  434,  434,
      435,  435,  435,  435,  435,  235,  435,  435,  435,  435,
      435,  436,  234,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  437,  233,  232,  437,  437,  437,  437,  437,

      437,  437,  437,  438,  438,  231,  230,  438,  229,  228,
      438,  439,  439,  227,  226,  439,  225,  224,  439,  440,
      440,  223,  440,  440,  440,  440,  440,  440,  440,  440,
      441,  441,  441,  442,  442,  443,  443,  444,  444,  222,
      221,  219,  218,  216,  215,  214,  213,  212,  211,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  193,  192,  187,  186,  172,  171,  167,
      165,  163,  160,  159,  158,  154,  151,  150,  149,  146,
      144,  141,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,

      122,  121,  118,  115,  111,  102,   91,   78,   77,   71,
       69,   67,   66,   65,   63,   57,   56,   54,   52,   51,
       49,   44,   43,   41,   34,   31,   23,   20,   15,   11,
        8,    7,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,

      426,  426,  426,  426,  426,  426,  426,  426,  426,  426
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.l"
/*DECLARACIONES*/




#line 31 "flex.l"
#include <stdio.h>
#include "scanner.h"
#include "bison.tab.h"
FILE *processed_file;
FILE *myfile;
FILE *output;
#define YY_DECL extern int yylex()
#define MAX_INCLUDE_DEPTH 10
#define MAX_DEFINE_STRUCT 100
YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;
int counter = 0;
int row = 1;
int column = 1;
char* aux_filename;
char* define_id;
char* define_value;
int i,j;
char* constant_sustitute = NULL;

typedef struct {
    char id[200];
    char value[200];
    struct define_struct *next;

}define_struct;

define_struct *first_define_node = NULL;
define_struct *last_define_node = NULL;
define_struct *current_define_node;


#line 850 "lex.yy.c"

#define INITIAL 0
#define include_found 1
#define comment_found 2
#define define_found 3
#define process_define_value 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 65 "flex.l"

#line 1074 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 427 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 833 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 66 "flex.l"
{ BEGIN(comment_found); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 67 "flex.l"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 68 "flex.l"
{ BEGIN(include_found); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 69 "flex.l"
{ BEGIN(define_found); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 71 "flex.l"
/* se come los espacios en blanco */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "flex.l"
{ /* obtiene el nombre de fichero a incluir */
    if ( include_stack_ptr >= MAX_INCLUDE_DEPTH ){
        fprintf( stderr, "Demasiados include anidados" );
        exit( 1 );
    }

    include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;
	aux_filename = malloc(strlen(yytext));
    for(i=j=0; i<strlen(yytext); i++){
        if(yytext[i] != '"' && yytext[i] != '<' && yytext[i] != '>'){
            aux_filename[j++] = yytext[i];
        }
    }
	aux_filename[j] = '\0';
    yyin = fopen(aux_filename, "r");
    if (!yyin)
        error("No se pudo abrir el archivo: %s\n", yytext);

    yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE));
    BEGIN(INITIAL);
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 94 "flex.l"

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 95 "flex.l"
{ BEGIN INITIAL; } /* Falta verificar que se cierre el comentario */
	YY_BREAK
case YY_STATE_EOF(comment_found):
#line 96 "flex.l"
{yyerror("Comentario sin cerrar\n"); yyterminate();}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 98 "flex.l"
/* se come los espacios en blanco */
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 99 "flex.l"
{ /* obtiene el ID */
    define_id = malloc(strlen(yytext)-1);
    for(i=j=0; i<strlen(yytext); i++){
        define_id[j] = yytext[i];
        j++;
    }
    define_id[j] = '\0';
    BEGIN(process_define_value);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 109 "flex.l"
/* se come los espacios en blanco */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "flex.l"
{ /* obtiene el valor del ID */
    define_value = malloc(strlen(yytext)-1);
    current_define_node = (define_struct *) malloc(sizeof(define_struct));

    define_value = malloc(strlen(yytext)-1);
    for(i=j=0; i<strlen(yytext); i++){
        define_value[j] = yytext[i];
        j++;
    }
    define_value[j] = '\0';

    /* verificar si el id ya esta en los defines*/
    define_struct *aux;
    aux = first_define_node;
    int id_found_flag = 0;

    while(aux != NULL){
        if(!strcmp(define_id, aux->id)){
            id_found_flag = 1;
            for(i=0; i<strlen(aux->value); i++){
                aux->value[i] = '\0';
            }
            memcpy(aux->value, define_value, sizeof(define_value));
            break;
        }

        aux = aux->next;
    }

    if(!id_found_flag){
        memcpy(current_define_node->id, define_id, sizeof(define_id));
        memcpy(current_define_node->value, define_value, sizeof(define_value));
        
    }else{
        id_found_flag = 0;
    }

    /* resetear los valores */
    for(i=0; i<strlen(define_id); i++){
        define_id[i] = '\0';
    }

    for(i=0; i<strlen(define_value); i++){
        define_value[i] = '\0';
    }

    current_define_node->next = NULL;

    if (first_define_node==NULL) {
        first_define_node = current_define_node;
        last_define_node = current_define_node;
    }
    else {
        /* el que hasta ahora era el último tiene que apuntar al nuevo */
        last_define_node->next = current_define_node;
        /* hacemos que el nuevo sea ahora el último */
        last_define_node = current_define_node;
    }
    
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(process_define_value):
#line 171 "flex.l"
{yyterminate();}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(include_found):
case YY_STATE_EOF(define_found):
#line 174 "flex.l"
{
    if ( --include_stack_ptr < 0 ){
        yyterminate();
    }

    else{
        yy_delete_buffer(YY_CURRENT_BUFFER );
        yy_switch_to_buffer(include_stack[include_stack_ptr] );
    }
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 187 "flex.l"
{ count(); write_to_processed_file(yytext); return(AUTO); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 188 "flex.l"
{ count(); write_to_processed_file(yytext); return(BREAK); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 189 "flex.l"
{ count(); write_to_processed_file(yytext); return(CASE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 190 "flex.l"
{ count(); write_to_processed_file(yytext); return(CHAR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 191 "flex.l"
{ count(); write_to_processed_file(yytext); return(CONST); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 192 "flex.l"
{ count(); write_to_processed_file(yytext); return(CONTINUE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 193 "flex.l"
{ count(); write_to_processed_file(yytext); return(DEFAULT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 194 "flex.l"
{ count(); write_to_processed_file(yytext); return(DO); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 195 "flex.l"
{ count(); write_to_processed_file(yytext); return(DOUBLE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 196 "flex.l"
{ count(); write_to_processed_file(yytext); return(ELSE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 197 "flex.l"
{ count(); write_to_processed_file(yytext); return(ENUM); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 198 "flex.l"
{ count(); write_to_processed_file(yytext); return(EXTERN); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 199 "flex.l"
{ count(); write_to_processed_file(yytext); return(FLOAT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 200 "flex.l"
{ count(); write_to_processed_file(yytext); return(FOR); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 201 "flex.l"
{ count(); write_to_processed_file(yytext); return(GOTO); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 202 "flex.l"
{ count(); write_to_processed_file(yytext); return(IF); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 203 "flex.l"
{ count(); write_to_processed_file(yytext); return(INLINE); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 204 "flex.l"
{ count(); write_to_processed_file(yytext); return(INT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 205 "flex.l"
{ count(); write_to_processed_file(yytext); return(LONG); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 206 "flex.l"
{ count(); write_to_processed_file(yytext); return(REGISTER); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 207 "flex.l"
{ count(); write_to_processed_file(yytext); return(RESTRICT); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 208 "flex.l"
{ count(); write_to_processed_file(yytext); return(RETURN); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 209 "flex.l"
{ count(); write_to_processed_file(yytext); return(SHORT); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 210 "flex.l"
{ count(); write_to_processed_file(yytext); return(SIGNED); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 211 "flex.l"
{ count(); write_to_processed_file(yytext); return(SIZEOF); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 212 "flex.l"
{ count(); write_to_processed_file(yytext); return(STATIC); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 213 "flex.l"
{ count(); write_to_processed_file(yytext); return(STRUCT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 214 "flex.l"
{ count(); write_to_processed_file(yytext); return(SWITCH); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 215 "flex.l"
{ count(); write_to_processed_file(yytext); return(TYPEDEF); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 216 "flex.l"
{ count(); write_to_processed_file(yytext); return(UNION); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 217 "flex.l"
{ count(); write_to_processed_file(yytext); return(UNSIGNED); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 218 "flex.l"
{ count(); write_to_processed_file(yytext); return(VOID); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 219 "flex.l"
{ count(); write_to_processed_file(yytext); return(VOLATILE); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 220 "flex.l"
{ count(); write_to_processed_file(yytext); return(WHILE); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 221 "flex.l"
{ count(); write_to_processed_file(yytext); return ALIGNAS; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 222 "flex.l"
{ count(); write_to_processed_file(yytext); return ALIGNOF; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 223 "flex.l"
{ count(); write_to_processed_file(yytext); return ATOMIC; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 224 "flex.l"
{ count(); write_to_processed_file(yytext); return BOOL; } 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 225 "flex.l"
{ count(); write_to_processed_file(yytext); return COMPLEX; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 226 "flex.l"
{ count(); write_to_processed_file(yytext); return GENERIC; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 227 "flex.l"
{ count(); write_to_processed_file(yytext); return IMAGINARY; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 228 "flex.l"
{ count(); write_to_processed_file(yytext); return NORETURN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 229 "flex.l"
{ count(); write_to_processed_file(yytext); return STATIC_ASSERT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 230 "flex.l"
{ count(); write_to_processed_file(yytext); return THREAD_LOCAL; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 231 "flex.l"
{ count(); write_to_processed_file(yytext); return FUNC_NAME; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 233 "flex.l"
{ count(); search_define_constant(); yylval.sval = strdup(yytext);
                          return check_type(); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 236 "flex.l"
{ count(); yylval.sval = strdup(yytext); write_to_processed_file(yytext); return I_CONSTANT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 237 "flex.l"
{ count(); yylval.sval = strdup(yytext); write_to_processed_file(yytext); return I_CONSTANT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 238 "flex.l"
{ count(); yylval.sval = strdup(yytext); write_to_processed_file(yytext); return I_CONSTANT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 239 "flex.l"
{ count(); yylval.sval = strdup(yytext); write_to_processed_file(yytext); return I_CONSTANT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 241 "flex.l"
{ count(); yylval.sval = strdup(yytext); write_to_processed_file(yytext); return F_CONSTANT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 242 "flex.l"
{ count(); yylval.sval = strdup(yytext); write_to_processed_file(yytext); return F_CONSTANT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 243 "flex.l"
{ count(); yylval.sval = strdup(yytext); write_to_processed_file(yytext); return F_CONSTANT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 244 "flex.l"
{ count(); yylval.sval = strdup(yytext); write_to_processed_file(yytext); return F_CONSTANT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 245 "flex.l"
{ count(); yylval.sval = strdup(yytext); write_to_processed_file(yytext); return F_CONSTANT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 246 "flex.l"
{ count(); yylval.sval = strdup(yytext); write_to_processed_file(yytext); return F_CONSTANT; }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 248 "flex.l"
{ count(); yylval.sval = strdup(yytext); format_string(yytext); return STRING_LITERAL;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 250 "flex.l"
{ count(); write_to_processed_file(yytext); return ELLIPSIS; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 251 "flex.l"
{ count(); write_to_processed_file(yytext); return RIGHT_ASSIGN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 252 "flex.l"
{ count(); write_to_processed_file(yytext); return LEFT_ASSIGN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 253 "flex.l"
{ count(); write_to_processed_file(yytext); return ADD_ASSIGN; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 254 "flex.l"
{ count(); write_to_processed_file(yytext); return SUB_ASSIGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 255 "flex.l"
{ count(); write_to_processed_file(yytext); return MUL_ASSIGN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 256 "flex.l"
{ count(); write_to_processed_file(yytext); return DIV_ASSIGN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 257 "flex.l"
{ count(); write_to_processed_file(yytext); return MOD_ASSIGN; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 258 "flex.l"
{ count(); write_to_processed_file(yytext); return AND_ASSIGN; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 259 "flex.l"
{ count(); write_to_processed_file(yytext); return XOR_ASSIGN; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 260 "flex.l"
{ count(); write_to_processed_file(yytext); return OR_ASSIGN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 261 "flex.l"
{ count(); write_to_processed_file(yytext); return RIGHT_OP; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 262 "flex.l"
{ count(); write_to_processed_file(yytext); return LEFT_OP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 263 "flex.l"
{ count(); write_to_processed_file(yytext); return INC_OP; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 264 "flex.l"
{ count(); write_to_processed_file(yytext); return DEC_OP; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 265 "flex.l"
{ count(); write_to_processed_file(yytext); return PTR_OP; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 266 "flex.l"
{ count(); write_to_processed_file(yytext); return AND_OP; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 267 "flex.l"
{ count(); write_to_processed_file(yytext); return OR_OP; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 268 "flex.l"
{ count(); write_to_processed_file(yytext); return LE_OP; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 269 "flex.l"
{ count(); write_to_processed_file(yytext); return GE_OP; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 270 "flex.l"
{ count(); write_to_processed_file(yytext); return EQ_OP; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 271 "flex.l"
{ count(); write_to_processed_file(yytext); return NE_OP; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 272 "flex.l"
{ count(); write_to_processed_file(yytext); return ';'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 273 "flex.l"
{ count(); write_to_processed_file(yytext); return '{'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 274 "flex.l"
{ count(); write_to_processed_file(yytext); return '}'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 275 "flex.l"
{ count(); write_to_processed_file(yytext); return ','; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 276 "flex.l"
{ count(); write_to_processed_file(yytext); return ':'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 277 "flex.l"
{ count(); write_to_processed_file(yytext); return '='; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 278 "flex.l"
{ count(); write_to_processed_file(yytext); return '('; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 279 "flex.l"
{ count(); write_to_processed_file(yytext); return ')'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 280 "flex.l"
{ count(); write_to_processed_file(yytext); return '['; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 281 "flex.l"
{ count(); write_to_processed_file(yytext); return ']'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 282 "flex.l"
{ count(); write_to_processed_file(yytext); return '.'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 283 "flex.l"
{ count(); write_to_processed_file(yytext); return '&'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 284 "flex.l"
{ count(); write_to_processed_file(yytext); return '!'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 285 "flex.l"
{ count(); write_to_processed_file(yytext); return '~'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 286 "flex.l"
{ count(); write_to_processed_file(yytext); return '-'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 287 "flex.l"
{ count(); write_to_processed_file(yytext); return '+'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 288 "flex.l"
{ count(); write_to_processed_file(yytext); return '*'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 289 "flex.l"
{ count(); write_to_processed_file(yytext); return '/'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 290 "flex.l"
{ count(); write_to_processed_file(yytext); return '%'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 291 "flex.l"
{ count(); write_to_processed_file(yytext); return '<'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 292 "flex.l"
{ count(); write_to_processed_file(yytext); return '>'; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 293 "flex.l"
{ count(); write_to_processed_file(yytext); return '^'; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 294 "flex.l"
{ count(); write_to_processed_file(yytext); return '|'; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 295 "flex.l"
{ count(); write_to_processed_file(yytext); return '?'; }
	YY_BREAK
case 116:
/* rule 116 can match eol */
YY_RULE_SETUP
#line 297 "flex.l"
{ count(); write_to_processed_file(yytext); /* whitespace separates tokens */ }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 298 "flex.l"
{ printLexicalErrors();/* discard bad characters */ }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 300 "flex.l"
ECHO;
	YY_BREAK
#line 1837 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 427 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 427 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 426);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 300 "flex.l"



int yywrap(void){       /* called at end of input */
    return 1;           /* terminate now */
}

static void comment(void){
    int c;

    while ((c = input()) != 0)
        if (c == '*')
        {
            while ((c = input()) == '*');

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
    yyerror("unterminated comment");
}

static int check_type(void){
    switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:                /* previously defined */
        return TYPEDEF_NAME;
    case ENUMERATION_CONSTANT:        /* previously defined */
        return ENUMERATION_CONSTANT;
    default:                          /* includes undefined */
        return IDENTIFIER;
    }
}

void count(){

	for (int i = 0; yytext[i] != '\0'; i++){
		if (yytext[i] == '\n'){
			column = 1;
          row++;
        }
		else if (yytext[i] == '\t'){
			column += 4 - (column % 4);
        }
		else{
			column++;
        }
    }
}

void printLexicalErrors(void){
	
	fprintf(stderr, "%s:%d:%d: %s%s: %s stray %s'%s' %s in program \n\n", COLOR_BLUE, row, column, COLOR_RED, "lexical error", COLOR_RESET, COLOR_YELLOW, yytext, COLOR_RESET);
	fprintf(stdout, "Fila:%d - Columna:%d : \n%s, %s: %s \n\n", row+1, column, "lexical error", "character unknown", yytext);
	counter++;
}

void search_define_constant(){
    define_struct *aux;
    aux = first_define_node;
    constant_sustitute = yytext;
    int constant_found_flag = 0;

    while(aux != NULL){
        //printf("Lista: %s\n", aux->id);
        if(!strcmp(yytext, aux->id)){
            constant_sustitute = aux->value;
            constant_found_flag = 1;
            break;
        }

        aux = aux->next;
    }

    if(constant_found_flag){
        write_to_processed_file(constant_sustitute);
        constant_found_flag = 0;
        
    }else{
        write_to_processed_file(yytext);
    }
    
}

void format_string(char* string){
    char aux[sizeof(string)+1];
    int index = 0;
    char* s;
    for(s = &string[0]; *s!='\0'; s++){
        if(*s == '%'){
            aux[index++] = *s;
        }
        aux[index++] = *s;
    }
    aux[index] = '\0';
    write_to_processed_file(aux);
}

void write_to_processed_file(char* string){
    fprintf(yyout, string);
}

